### ISSUE TITLE
Suggestion: Support multiple Rimworld versions

### ISSUE THREAD

**Issue by Annehilator** [NigrumMortis/ExpandedRoofing#3]
If possible test this mod with versions like e.g. 1.3 and 1.2.
If it works you could add them as tags to the workshop :)

**Comment by NigrumMortis** [comment]
This was also already dicscussed on steam. Thanks for opening the issue here. I will look into that.

**Comment by NigrumMortis** [comment]
Done

**Comment by NigrumMortis** [comment]
Will not do
